"""In-memory model provider for deterministic LLM reasoning and tests."""

import json
from typing import Any


class InMemoryModelProvider:
    """Provides deterministic structured model completions for testing and examples.

    Does not bypass reasoning, grounding, security firewall, or policy checks.
    """

    def __init__(
        self,
        default_response: str | dict[str, Any] | None = None,
        responses: dict[str, str | dict[str, Any]] | None = None,
    ) -> None:
        if isinstance(default_response, dict):
            self.default_response = json.dumps(default_response)
        elif default_response is not None:
            self.default_response = str(default_response)
        else:
            self.default_response = json.dumps(
                {
                    "title": "Model Inferred Root Cause",
                    "description": "Deterministic diagnostic hypothesis generated by InMemoryModelProvider.",
                    "reasoning": "Correlated evidence patterns match memory model rules.",
                }
            )

        self.responses: dict[str, str] = {}
        if responses:
            for k, v in responses.items():
                self.responses[k] = json.dumps(v) if isinstance(v, dict) else str(v)

        self.call_history: list[dict[str, Any]] = []

    def set_response_for_prompt_substring(
        self, substring: str, response: str | dict[str, Any]
    ) -> None:
        """Register specific response for prompt containing substring."""
        self.responses[substring] = json.dumps(response) if isinstance(response, dict) else str(response)

    async def generate(
        self,
        prompt: str,
        temperature: float = 0.0,
        max_tokens: int = 1024,
        system_instruction: str | None = None,
        context: dict[str, Any] | None = None,
    ) -> str:
        """Generate deterministic structured response."""
        self.call_history.append(
            {
                "prompt": prompt,
                "temperature": temperature,
                "max_tokens": max_tokens,
                "system_instruction": system_instruction,
                "context": context,
            }
        )

        for substring, resp in self.responses.items():
            if substring in prompt:
                return resp

        return self.default_response


__all__ = ["InMemoryModelProvider"]
